import React, { ReactElement } from 'react';
import Document, { Head, Html, Main, NextScript } from 'next/document';

export default class _Document extends Document {
  render(): ReactElement {
    return (
      <Html>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
        <style>`
        `</style>
      </Html>
    );
  }
}
